{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: automated-listing-engine-api
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: automated-listing-engine-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - action: replace
          targetLabel: use_case
          replacement: automated-listing-engine
{{- end }}
