{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - action: replace
          targetLabel: use_case
          replacement: {{ .Values.useCase }}
{{- end }}
